server:
 port: 60011
 
eureka:
 instance:
  hostname: peer2
 server:
  enableSelfPreservation: false
# client:
#  register-with-eureka: false
#  fetch-registry: false
  serviceUrl:
   defaultZone: http://${totoro.host}:60011/eureka